/* 
Babarpur Extension,
Mauzpur,
Zafarabad School,
Eidgah,
Police Station Zafarabad,
Seelampur,
Parsvnath Metro Mall-Seelampur,
Seelampur Metro Station,
Dharam Pura,
Shastri Park,
Shri Shyam Girimath Mandir,
Shastri Park Metro Depot,
Nityanand Marg,
Tis Hazari Court,
Saint Stephens Hospital,
Baraf Khana,
Azad Market / DCM,
Bara Hindu Rao,
Filmistan,
Model Basti,
Idgah,
Guru Govind Singh Crossing,
Faiz Road,
Prahlad Market,
Khalsa College,
Regharpura,
R.S. Satsang,
Rajendra Place,
East Patel Nagar,
Patel Nagar Metro Station,
West Patel Nagar,
Shadipur Metro Station,
Shadipur Depot 
*/

/* //
const stops = [
    Babarpur Extension,
    Mauzpur,
    Zafarabad School,
    Eidgah,
    Police Station Zafarabad,
    Seelampur,
    Parsvnath Metro Mall-Seelampur,
    Seelampur Metro Station,
    Dharam Pura,
    Shastri Park,
    Shri Shyam Girimath Mandir,
    Shastri Park Metro Depot,
    Nityanand Marg,
    Tis Hazari Court,
    Saint Stephens Hospital,
    Baraf Khana,
    Azad Market / DCM,
    Bara Hindu Rao,
    Filmistan,
    Model Basti,
    Idgah,
    Guru Govind Singh Crossing,
    Faiz Road,
    Prahlad Market,
    Khalsa College,
    Regharpura,
    R.S. Satsang,
    Rajendra Place,
    East Patel Nagar,
    Patel Nagar Metro Station,
    West Patel Nagar,
    Shadipur Metro Station,
    Shadipur Depot
  ]; */


 